name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout current repository"
        uses: actions/checkout@v6
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Set up Biome
        uses: biomejs/setup-biome@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Ensure build ok
        run: bun run build
      - name: Generate definitions
        run: bun run definitions
      - name: Run all tests
        run: bun test
